# Generated by Django 2.2 on 2020-05-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restuarants',
            new_name='Restaurant',
        ),
    ]
