# Generated by Django 2.2 on 2020-05-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0003_auto_20200514_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='RestaurantLocation',
        ),
    ]
